<a href="https://colab.research.google.com/github/Sergio-doke/Analisis_Titanic/blob/main/Entrega_26111_SergioFernandez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 📘 Pre-entrega

**Nombre del alumno:** Sergio Fernandez

# 🧩 Etapa 1: Recopilación y Preparación de Datos
**Objetivo:** Demostrar habilidades en Python, familiaridad con el entorno de trabajo y conocimientos básicos sobre manipulación de datos.

### #1 Carga de datos

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# TODO: Cargar los datasets como DataFrames usando pandas.
# Sugerencia: utilizar pd.read_csv() para cargar los archivos CSV.
# Recordá verificar la ruta correcta y revisar las primeras filas con .head().
import pandas as pd
ventas = pd.read_csv('/content/drive/MyDrive/Datasets/ventas.csv')
marketing = pd.read_csv('/content/drive/MyDrive/Datasets/marketing.csv')
clientes = pd.read_csv('/content/drive/MyDrive/Datasets/clientes.csv')

In [6]:
ventas

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos
...,...,...,...,...,...,...
3030,1837,Horno eléctrico,$104.12,9.0,30/12/2024,Electrodomésticos
3031,2276,Laptop,$85.27,9.0,30/12/2024,Electrónica
3032,2696,Laptop,$107.81,4.0,30/12/2024,Electrónica
3033,2913,Smartphone,$99.85,7.0,30/12/2024,Electrónica
3034,2930,Consola de videojuegos,$55.47,6.0,30/12/2024,Electrónica

In [ ]:
marketing

In [8]:
clientes.head()

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

### #4 Análisis exploratorio inicial

In [9]:
# TODO: Realizar un análisis exploratorio inicial de los DataFrames.
# Sugerencia: usar métodos como .info(), .describe(), .shape y .columns. dtypes.
# Esto te ayudará a entender la estructura y el contenido de los datos.
# Podés incluir comentarios sobre observaciones iniciales.
def eda(df, nombre):
    print(f"=== {nombre} ===") #muestra el nombre
    print("shape:", df.shape)  # cantidad de filas, columnas
    print("columnas:", list(df.columns)) #lista nombres de columnas
    print("dtypes:")
    print(df.dtypes)                     #muestra el tipo de dato
    print("\nNulos por columna:")
    print(df.isna().sum())               #suma valores faltantes
    print("\nPrimeras filas:")
    display(df.head(5))                  #trae 5 primeros registros
    print("\nDescribe (numérico):")
    display(df.describe(include='number')) #datos de estadistica
    print("-"*100)

In [10]:
eda(ventas, "Analísis explotario de datos de ventas")

=== Analísis explotario de datos de ventas ===
shape: (3035, 6)
columnas: ['id_venta', 'producto', 'precio', 'cantidad', 'fecha_venta', 'categoria']
dtypes:
id_venta         int64
producto        object
precio          object
cantidad       float64
fecha_venta     object
categoria       object
dtype: object

Nulos por columna:
id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Primeras filas:

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

Describe (numérico):

          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000

----------------------------------------------------------------------------------------------------

In [11]:
eda(marketing, "Analísis explotario de datos de ventas")

=== Analísis explotario de datos de ventas ===
shape: (90, 6)
columnas: ['id_campanha', 'producto', 'canal', 'costo', 'fecha_inicio', 'fecha_fin']
dtypes:
id_campanha       int64
producto         object
canal            object
costo           float64
fecha_inicio     object
fecha_fin        object
dtype: object

Nulos por columna:
id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64

Primeras filas:

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

Describe (numérico):

       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000

----------------------------------------------------------------------------------------------------

In [12]:
eda(clientes, "Analísis explotario de datos de ventas")

=== Analísis explotario de datos de ventas ===
shape: (567, 5)
columnas: ['id_cliente', 'nombre', 'edad', 'ciudad', 'ingresos']
dtypes:
id_cliente      int64
nombre         object
edad            int64
ciudad         object
ingresos      float64
dtype: object

Nulos por columna:
id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64

Primeras filas:

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

Describe (numérico):

       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000

----------------------------------------------------------------------------------------------------

### #5 Calidad de los datos

In [ ]:
# TODO: Identificar valores nulos y duplicados en los conjuntos de datos.
# Sugerencia: usar .isna().sum() y .duplicated().sum().
# Documentar las observaciones con print() o comentarios.

In [13]:
# DataFrame: ventas
# =========================================

# 1. Ver los primeros datos
print("Primeras filas del DataFrame:")
display(ventas.head())
# 2. Valores nulos
# -----------------------------------------
nulos = ventas.isna().sum()
print("\nCantidad de valores nulos por columna:")
display(nulos)
# -----------------------------------------
# 3. Filas duplicadas completas
# -----------------------------------------
duplicados = ventas.duplicated().sum()
print("\nCantidad de filas duplicadas:", duplicados)
# -----------------------------------------
# 4. Duplicados por id de venta
# -----------------------------------------
duplicados_id = ventas['id_venta'].duplicated().sum()
print("\nDuplicados en 'id_venta':", duplicados_id)
# -----------------------------------------
# 5. Valores más repetidos en id_venta
# -----------------------------------------
repetidos = ventas['id_venta'].value_counts()

print("\nValores más repetidos en 'id_venta':")
display(repetidos.head(5))

Primeras filas del DataFrame:

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

Cantidad de valores nulos por columna:

id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Cantidad de filas duplicadas: 35

Duplicados en 'id_venta': 35

Valores más repetidos en 'id_venta':

id_venta
2356    2
2096    2
2085    2
1956    2
1642    2
Name: count, dtype: int64

In [18]:
def analisis_inicial(df, nombre_df="DataFrame", columna_id=None):

    print(f"===== Análisis de {nombre_df} =====")
    print("\nPrimeras filas del DataFrame:")
    display(df.head())
    nulos = df.isna().sum()
    print("\nCantidad de valores nulos por columna:")
    display(nulos)
    duplicados = df.duplicated().sum()
    print("\nCantidad de filas duplicadas:", duplicados)
    if columna_id and columna_id in df.columns:
        duplicados_id = df[columna_id].duplicated().sum()
        print(f"\nDuplicados en '{columna_id}':", duplicados_id)
        repetidos = df[columna_id].value_counts()
        print(f"\nValores más repetidos en '{columna_id}':")
        display(repetidos.head(5))
    print("\n" + "="*80)

In [19]:
analisis_inicial(ventas, "Ventas", "id_venta")

===== Análisis de Ventas =====

Primeras filas del DataFrame:

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

Cantidad de valores nulos por columna:

id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Cantidad de filas duplicadas: 35

Duplicados en 'id_venta': 35

Valores más repetidos en 'id_venta':

id_venta
2356    2
2096    2
2085    2
1956    2
1642    2
Name: count, dtype: int64

================================================================================

In [22]:
analisis_inicial(clientes, "Clientes", "id_cliente")

===== Análisis de Clientes =====

Primeras filas del DataFrame:

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

Cantidad de valores nulos por columna:

id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64

Cantidad de filas duplicadas: 0

Duplicados en 'id_cliente': 0

Valores más repetidos en 'id_cliente':

id_cliente
567    1
1      1
2      1
3      1
4      1
Name: count, dtype: int64

================================================================================

In [23]:
analisis_inicial(marketing, "martketing","id_campanha")

===== Análisis de martketing =====

Primeras filas del DataFrame:

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

Cantidad de valores nulos por columna:

id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64

Cantidad de filas duplicadas: 0

Duplicados en 'id_campanha': 0

Valores más repetidos en 'id_campanha':

id_campanha
74    1
12    1
32    1
21    1
58    1
Name: count, dtype: int64

================================================================================

# 🧹 Etapa 2: Preprocesamiento y Limpieza de Datos
**Objetivo:** Demostrar conocimiento de las técnicas de limpieza y transformación de datos.

### #1 Limpieza de datos

In [24]:
# TODO: Limpiar el conjunto de datos eliminando duplicados y caracteres no deseados.
# Sugerencia: aplicar .drop_duplicates(), .str.strip(), .str.replace() según el caso.
# Documentar el proceso y los resultados.
# Creamos copias independientes para no modificar los  dataframes originales se usa en arquitectura Medallion, Bronze
ventas_clean = ventas.copy()
clientes_clean = clientes.copy()
marketing_clean = marketing.copy()

In [26]:
ventas_clean["producto"] = (
    ventas_clean["producto"]
    .astype(str) # → convierte todo a texto; no tiene parámetros adicionales.
    .str.title() # Convierte a Título: "juan pérez" → "Juan Pérez"
    .str.strip() # Elimina espacios al inicio y final
    .str.replace( " +"," ", regex=True)  # reemplaza "uno o más espacios consecutivos" por un solo espacio
)
#ventas_clean["producto"] = ventas_clean["producto"].astype(str).str.title().str.strip().str.replace(" +", " ", regex=True)
ventas_clean["categoria"] = (
    ventas_clean["categoria"]
    .astype(str) #→ convierte todo a texto; no tiene parámetros adicionales.
    .str.title() # Convierte a Título: "juan pérez" → "Juan Pérez"
    .str.strip() # Elimina espacios al inicio y final
    .str.replace(" +", " ", regex=True)  # reemplaza "uno o más espacios consecutivos" por un solo espacio
)
ventas.head(5)
ventas.dtypes

id_venta         int64
producto        object
precio          object
cantidad       float64
fecha_venta     object
categoria       object
dtype: object

In [29]:
ventas_clean["fecha_venta"] = pd.to_datetime(ventas_clean["fecha_venta"], errors="coerce", dayfirst=True)
marketing_clean["fecha_inicio"] = pd.to_datetime(marketing_clean["fecha_inicio"], errors="coerce", dayfirst=True)
marketing_clean["fecha_fin"] = pd.to_datetime(marketing_clean["fecha_fin"], errors="coerce", dayfirst=True)

In [31]:
ventas_clean.head(5)

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro Decorativo,$69.94,5.0,2024-01-02,Decoración
1,811,Lámpara De Mesa,$105.10,5.0,2024-01-02,Decoración
2,1156,Secadora,$97.96,3.0,2024-01-02,Electrodomésticos
3,1372,Heladera,$114.35,8.0,2024-01-02,Electrodomésticos
4,1546,Secadora,$106.21,4.0,2024-01-02,Electrodomésticos

In [32]:
marketing_clean.head(5)

   id_campanha         producto  canal  costo fecha_inicio  fecha_fin
0           74  Adorno de pared     TV   4.81   2024-03-20 2024-05-03
1           12           Tablet   RRSS   3.40   2024-03-26 2024-05-13
2           32  Lámpara de mesa  Email   5.54   2024-03-28 2024-04-20
3           21       Smartphone   RRSS   6.37   2024-03-29 2024-05-16
4           58         Alfombra  Email   4.25   2024-03-31 2024-05-05

In [33]:
ventas_clean.head()

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro Decorativo,$69.94,5.0,2024-01-02,Decoración
1,811,Lámpara De Mesa,$105.10,5.0,2024-01-02,Decoración
2,1156,Secadora,$97.96,3.0,2024-01-02,Electrodomésticos
3,1372,Heladera,$114.35,8.0,2024-01-02,Electrodomésticos
4,1546,Secadora,$106.21,4.0,2024-01-02,Electrodomésticos

In [34]:
#normalizar el precio, sacandole el $
 # Se usa nuevamente agrupación con () para encadenar métodos y mantener legibilidad
ventas_clean["precio"] = (
        ventas_clean["precio"]
        .astype(str)                        # Convierte todo a texto
        .str.replace("$", "", regex=False)  # Elimina el símbolo $
        #   "$" → texto literal a reemplazar
        #   ""  → nuevo valor (vacío)
        #   regex=False → interpreta "$" literalmente, no como expresión regular
        .str.replace(",", "", regex=False)  # Elimina comas de miles 1,000  1000
        .str.strip()                        # Quita espacios sobrantes
    )
ventas_clean["precio"] = pd.to_numeric(ventas_clean["precio"], errors="coerce")

In [36]:
ventas_clean.head(5)
#ventas_clean.dtypes

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro Decorativo,69.94,5.0,2024-01-02,Decoración
1,811,Lámpara De Mesa,105.10,5.0,2024-01-02,Decoración
2,1156,Secadora,97.96,3.0,2024-01-02,Electrodomésticos
3,1372,Heladera,114.35,8.0,2024-01-02,Electrodomésticos
4,1546,Secadora,106.21,4.0,2024-01-02,Electrodomésticos

In [37]:
ventas_clean["cantidad"] = pd.to_numeric(ventas_clean["cantidad"], errors="coerce").astype("Int64")

In [38]:
print(ventas_clean.dtypes)

id_venta                int64
producto               object
precio                float64
cantidad                Int64
fecha_venta    datetime64[ns]
categoria              object
dtype: object

In [40]:

# 3 Completar valores null con 0
ventas_clean = ventas_clean.fillna(0)

#elimino filas que en la columna precio o cantidad tengan NaN, siempre y cuando
#no afecte a estadisticas finales, depende el analisis que realice del dato
ventas_clean = ventas_clean.dropna(subset=["precio", "cantidad"])


#Solo 0 en cantidad y precio con el precio del articulo, cuando ya tenemos el precio convertido en float
ventas_clean["cantidad"] = ventas_clean["cantidad"].fillna(0)
#agrupo por producto, me quedo con el precio, y a ese precio lo transformo en el promedio de cada fila que es x aplico una lambda.
#a la columna precio le coloco en el caso de que la celda este null en una fila, el promedio de los precios del mismo producto
ventas_clean["precio"] = ventas_clean.groupby("producto")["precio"].transform(
    lambda x: x.fillna(x.mean())
)
'''
transform() devuelve un resultado del mismo tamaño que el DataFrame original.

Eso es importante porque:

groupby() separa en grupos
transform() permite volver a colocar el resultado fila por fila
x.fillna(x.mean())

Reemplaza los NaN del grupo por el promedio del grupo.
'''

#verificamos null
print(ventas_clean.isna().sum())

id_venta       0
producto       0
precio         0
cantidad       0
fecha_venta    0
categoria      0
dtype: int64

In [41]:
ventas_clean = ventas_clean.drop_duplicates()
clientes_clean = clientes_clean.drop_duplicates()
marketing_clean = marketing_clean.drop_duplicates()

In [42]:
ventas_clean.head(5)

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro Decorativo,69.94,5,2024-01-02,Decoración
1,811,Lámpara De Mesa,105.10,5,2024-01-02,Decoración
2,1156,Secadora,97.96,3,2024-01-02,Electrodomésticos
3,1372,Heladera,114.35,8,2024-01-02,Electrodomésticos
4,1546,Secadora,106.21,4,2024-01-02,Electrodomésticos

### #2 Transformación de datos

In [ ]:
# TODO: Aplicar filtros y transformaciones para crear una tabla de ventas
# que muestre solo los productos con alto rendimiento. calcular el percentil 80
# y filtrar los productos que superen ese umbral en ventas.
#quantile(0.8)
# Sugerencia: usar .query() o condiciones con operadores lógicos.

In [44]:
ventas_clean = ventas_clean.assign(
        total = ventas_clean["precio"] * ventas_clean["cantidad"]
        # assign(**nuevas_col): crea nuevas columnas y devuelve una copia del DF.
        # Alternativa: ventas_clean["ingreso"] = ventas_clean["precio"] * ventas_clean["cantidad"]
    )

In [48]:
ventas_clean.head(5)

,id_venta,producto,precio,cantidad,fecha_venta,categoria,total
0,792,Cuadro Decorativo,69.94,5,2024-01-02,Decoración,349.7
1,811,Lámpara De Mesa,105.10,5,2024-01-02,Decoración,525.5
2,1156,Secadora,97.96,3,2024-01-02,Electrodomésticos,293.88
3,1372,Heladera,114.35,8,2024-01-02,Electrodomésticos,914.8
4,1546,Secadora,106.21,4,2024-01-02,Electrodomésticos,424.84

In [50]:
# Crear columna total
ventas_clean = ventas_clean.assign(
    total = ventas_clean["precio"] * ventas_clean["cantidad"]
)

# Calcular percentil 80
umbral = ventas_clean["total"].quantile(0.8)

print("Percentil 80:", umbral)

# Filtrar productos de alto rendimiento
ventas_alto_rendimiento = ventas_clean.query("total > @umbral")

# Ver resultados
display(ventas_alto_rendimiento.head())

Percentil 80: 787.3120000000001

/tmp/ipykernel_28285/3242043986.py:12: RuntimeWarning: Engine has switched to 'python' because numexpr does not support extension array dtypes. Please set your engine to python manually.
  ventas_alto_rendimiento = ventas_clean.query("total > @umbral")

,id_venta,producto,precio,cantidad,fecha_venta,categoria,total
3,1372,Heladera,114.35,8,2024-01-02,Electrodomésticos,914.8
7,2959,Proyector,88.17,9,2024-01-02,Electrónica,793.53
8,318,Rincón De Plantas,79.86,11,2024-01-03,Decoración,878.46
19,882,Cuadro Decorativo,101.92,9,2024-01-04,Decoración,917.28
20,969,Candelabro,90.70,12,2024-01-04,Decoración,1088.4

### #3 Agregación

In [ ]:
# TODO: Resumir las ventas por categoría de producto y analizar los ingresos generados.
# Sugerencia: usar .groupby() y .agg() para generar métricas como suma y promedio.

In [52]:
resumen_producto = (

    ventas_clean

    .groupby(
        by="producto",
        dropna=False,
        as_index=False,
        observed=False
    )

    .agg(
        ingreso_total=('total', 'sum'),
        unidades=('cantidad', 'sum'),
        precio_promedio=('precio', 'mean'),
        registros=('total', 'size')
    )

)

# Mostrar resultados
display(resumen_producto.head())

          producto  ingreso_total  unidades  precio_promedio  registros
0  Adorno De Pared       48093.49       633        76.097800        100
1         Alfombra       44773.06       615        74.098300        100
2       Aspiradora       50085.86       651        77.447400        100
3      Auriculares       74175.58       958        76.302727        143
4         Batidora        50979.2       672        77.537200        100

In [53]:
top_productos = resumen_producto.sort_values(
    by="ingreso_total",
    ascending=False
)

display(top_productos.head(10))

             producto  ingreso_total  unidades  precio_promedio  registros
19    Lámpara De Mesa       82276.38      1112        72.720625        176
3         Auriculares       74175.58       958        76.302727        143
20         Microondas       72562.89       912        79.176000        135
5            Cafetera       59607.31       765        79.046581        117
9   Cuadro Decorativo        54297.6       726        74.578000        100
26         Smartphone       54132.44       665        81.398416        101
25           Secadora       52115.45       696        73.338900        100
16  Jarrón Decorativo       51130.88       672        74.534000        100
4            Batidora        50979.2       672        77.537200        100
24  Rincón De Plantas       50456.45       691        74.823861        101

In [54]:
mas_vendidos = resumen_producto.sort_values(
    by="unidades",
    ascending=False
)

display(mas_vendidos.head(10))

             producto  ingreso_total  unidades  precio_promedio  registros
19    Lámpara De Mesa       82276.38      1112        72.720625        176
3         Auriculares       74175.58       958        76.302727        143
20         Microondas       72562.89       912        79.176000        135
5            Cafetera       59607.31       765        79.046581        117
9   Cuadro Decorativo        54297.6       726        74.578000        100
25           Secadora       52115.45       696        73.338900        100
24  Rincón De Plantas       50456.45       691        74.823861        101
4            Batidora        50979.2       672        77.537200        100
16  Jarrón Decorativo       51130.88       672        74.534000        100
18           Lavadora       48946.44       671        74.953400        100

In [55]:
# Resumen por categoria
# 3) Agregación por categoría con groupby + agg
resumen_categoria = (
    ventas_clean
    .groupby(
        by="categoria",      # Puede ser string o lista de strings si quisiéramos agrupar por varias columnas.
        dropna=False,    # Mantener grupo NaN (si hay filas sin categoría).
        as_index=False   # Dejar la categoría como columna normal (y no como índice).
        # observed: si cat_col es 'category' y queremos mostrar solo categorías presentes → True.
    )
    .agg(
        ingreso_total=('total', 'sum'),   # Suma total de ingresos por categoría.
        unidades=('cantidad', 'sum'),       # Unidades totales vendidas en la categoría.
        ventas=('total', 'size'),         # Cantidad de registros/filas (ventas) en la categoría.
        precio_promedio=('precio', 'mean')  # Precio promedio observado en la categoría.
        # Otras funciones útiles: 'median','max','min','std','var','nunique'...
    )
    .sort_values(
        by='ingreso_total', # Ordenar por ingreso total
        ascending=False,    # Descendente: mayores arriba
        na_position='last', # NaN al final
        ignore_index=True   # Reindexar desde 0
    )
)

# 4) Ticket promedio por venta = ingreso_total / ventas
resumen_categoria = resumen_categoria.assign(
    ticket_promedio_por_venta = resumen_categoria['ingreso_total'] / resumen_categoria['ventas']
    # assign: crea/reescribe columnas. Alternativa: resumen_cat['ticket_promedio_por_venta'] = ...
)

print("Resumen por categoría (ordenado por ingreso_total):")
display(resumen_categoria.head(20))

Resumen por categoría (ordenado por ingreso_total):

,categoria,ingreso_total,unidades,ventas,precio_promedio,ticket_promedio_por_venta
0,Electrodomésticos,505299.63,6592,1000,76.520960,505.29963
1,Electrónica,482577.8,6413,999,75.253247,483.060861
2,Decoración,479216.09,6490,1001,74.095516,478.737353

### #4 Integración de datos, opcional, NO OBLIGATORIO

In [ ]:
# TODO: Combinar los sets de datos de ventas y marketing para obtener una visión más amplia de las tendencias.
# Sugerencia: usar pd.merge() especificando la clave común entre ambos DataFrames.
# Documentar cualquier observación relevante sobre la combinación de datos.